In [3]:
import pandas as pd
import json
import os
import glob
import nltk
import string as st

In [6]:
# Based on Piazza post @317

path = './dataset'
glob_target = os.path.join(path,'*.json')
file_list = glob.glob(glob_target)

file_count = 0
json_email_df_list = []
for file in file_list:
    with open(file) as f:
        json_data = pd.json_normalize(json.loads(f.read()))
        file_name = file.split('/')[2].split('.')[0]
        json_data['filename'] = file_name
        json_email_df_list.append(json_data)        
        print(file.split('/')[2].split('.')[0])
df = pd.concat(json_email_df_list, sort=False)
df.reset_index(inplace=True)

5c7b50433b3e53a8af2acce8bb6b1284
500de76031fa71fe44c235de425b62ab
ce7c3f7a4b4b32a8ecfebc4b3ccb5ad8
0ca99267aa67cfe2acf078403ea861ae
4bd9af6f563313a2af55fc9e140f3e46
3e8d4f0c5214de433ffc72c80c81a392
8268721691e50ea03b42cd693868c5ce
979850a4898dc2bc16939185d92c6c69
f3931da88a424220f155cd2852906c2a
5597f10da58452d79406ca9b4f035cab
a2f712b85c54e810b0a6dcca512afc0f
3f9cebd9b4a3b55d0c761a81badf43d6
3a9af32826a723b9c87768bcb142fd13
a95a146c13149c6883b371ba4a6aad2d
d1b9e699599b97f7fea095d0b5471127
f473b4a4613957068ba026ab3671cad1
a62456f5707cfad94d287f035c34d148
08a6401f8b06c6449378329d31abce2e
aeb1154e1bf165dbd8a0edfc46e74653
69e2a3a841cba3721e1a16743fe0c8b1
4d0d73acbc0c0bd07d1c0b548ca368dd
7f47bf20fd56fe32bd00e019b50ae868
75fdf988581374b7c410ce735c6e26b5
dc57ad494fc91a54d9f643598dd2d1d7
6b9174f02efea97e6dddeb5ef5eb4998
fb8e468d0f09ca82e138f97f1e69344b
5dc15164a2c250ec1716891acefa99d8
c85c95b5b2a0bb715181940efc1f1939
2f02ce972903ff4c63ed7039d68822e7
f7b3f0b9e56febaa4d597ebe6de8f729
5d649dfd958e80e9263fd4e20d899094
3f2ee97ced1029240b174b052d05c153
0cf803b90f5e12f9162164369abb2034
522747e8904f1cb6ea1ed78e65898519
e91dcaf847d3bf94c14a1b41ba23a8c9
f8166368b710836b4a996baaff89e924
7e83316732bed6db7ef4268ea9a17879
f91e543785ad81121f5d26c5adfb9a88
93116194880251571ceaedd33e2876d5
cd8072e326e93a23350ac388346ed60d
31a8857bd9ab9b99df4ba8f10fdcd31d
a3abb76cdfd9fad82a4301117cdbbe76
d81359af9359a829515ec495ea5a9afb
5c7d6867dd46a7de74cf8f2d787d8086
a84c7aa1c48fa5b7392774904b1b8449
bcf879b8cafb2612b46b682577934d4b
56a6091b129a823c1e3b75bbbcb88a22
759acaa941119dcb72142c81c3a9bb51
089ea6336cbadadcc4980b86d54dc852
0ef8999e47057041b2d396a11262804b
adc670ff5c47ab9bf4b91154f0d4e1de
9ed515d69e1c50797808edc88b0efe90
46a0cf4dbdd325a465219f877a8a7b32
f0ed6146a097c6ecd53031138d2f7ed3
d6900054b0574bb1c550ad3469abf4c8
7fa4c1e14a2e60ca4350daeadfc2a28d
5ce0d6cf4d29fb66368cb99c247d68cf
55aaa37d3507851169c680393bdb7425
87cd6cd932ac6d44fd08d340df4faf1a
fff0108998da86be2ce1263e84ae0494
6b2c1e3f42d517b3e1dd71f5b08ed384
7b605fbe9fb06d1e79f7859fdf20a5cf
dcf40892d4d1aba6b393982037c2ffad
64961a614c15b994889ae120c5d29389
9b6afc7ef713a718d0c1f42c64f77b2c
7618396a9340ac660458cda37dedbbca
5692b037680da78ce693aad83605750f
a2bfc6f99aacc3db7f5fb19d7d05904c
bf7453ee5ae6a2874e0af444769c95bf
689f777abe6ec678dce6fe3dff596e60
c82cc99f2f4dfb035a47285bcc940fb4
7cc4c22655f82472665e1ac8a73cce2a
6efd52595a376badb5dc14e852c16c2b
9a40f55b66d1aa7ef4fc462b1e752bd9
b4c41033e6e8f06a3a90ec36ddbec97d
51baa99cff57242bb28645441f0dc0ca
5c29ff3ccc68c43dc8ea2367341307b1
bc43687c72faa7620be184c98f41af33
07f00d5f1b7c5e00a166fe0c0850d4c5
f4f591b913fa14e85f454791e1b653c5
01a1aeb214a999b8c59db0d30e566147
c482f009e76f7a096ea60b831a13141c
d8b1b8347319d4fb26ba355fb6837629
f9477039eba5b9a4bb77c7e490ae0c28
d9f7d466d37e89816c30c63b4d4fae9d
260ba5bb6ef7a662a7b0d2358395cdff
6a62353dcbdb679873bb8586599b7c47
f18c0d863b33dde562e4c6b9f74f89e6
9fc0df1b1c9bd671b1db67c09cd1a397
13656503f8678d6119a661ae6a5bd8d6
469acdf6fd6774663e939441fb906632
a3d1f9d13e70da49b9d141e40ef7b96e
699cf30ff599aa26e3a8fa1e52c684b5
a20da08818db2c180706efd1248e98e7
473546672626c7a8dd2a6f4db1096e9e
4d57a0b6a17f57461ab4a89eef06f56b
d8cb2bc98760e8c4628ab1bb235febdd
d67f302391a1230c166dcbbd5a970364
a67762fd8e81411ca397870469ffbb42

In [7]:
df.head()

,index,text,subject,messageId,priority,from,to,date,headers.message-id,headers.date,...,headers.x-cc,headers.x-bcc,headers.x-folder,headers.x-origin,headers.x-filename,filename,cc,bcc,headers.cc,headers.bcc
0,0,---------------------- Forwarded by Rika Imai/...,4 Month Rolling Forecast,88180.1075863689140.JavaMail.evans@thyme,normal,"[{'address': 'rika.imai@enron.com', 'name': ''}]","[{'address': 'john.forney@enron.com', 'name': ...",2001-05-08T15:37:00.000Z,<88180.1075863689140.JavaMail.evans@thyme>,"Tue, 8 May 2001 08:37:00 -0700 (PDT)",...,,,\Rob_Benson_Jun2001\Notes Folders\Notes inbox,Benson-R,rbenson.nsf,5c7b50433b3e53a8af2acce8bb6b1284,NaN,NaN,NaN,NaN
1,0,great,Re: Jim Simpson,4460514.1075857469666.JavaMail.evans@thyme,normal,"[{'address': 'hunter.shively@enron.com', 'name...","[{'address': 'richard.tomaski@enron.com', 'nam...",2000-06-21T09:01:00.000Z,<4460514.1075857469666.JavaMail.evans@thyme>,"Wed, 21 Jun 2000 02:01:00 -0700 (PDT)",...,,,\Hunter_Shively_Jun2001\Notes Folders\Sent,Shively-H,hshivel.nsf,500de76031fa71fe44c235de425b62ab,NaN,NaN,NaN,NaN
2,0,"oohh la la. who was your ""friend""? did you g...",Re: Re[2]:,2160301.1075858147494.JavaMail.evans@thyme,normal,"[{'address': 'matthew.lenhart@enron.com', 'nam...","[{'address': 'shelliott@dttus.com', 'name': ''}]",2000-08-16T10:03:00.000Z,<2160301.1075858147494.JavaMail.evans@thyme>,"Wed, 16 Aug 2000 03:03:00 -0700 (PDT)",...,,,\Matthew_Lenhart_Jun2001\Notes Folders\Sent,Lenhart-M,mlenhar.nsf,ce7c3f7a4b4b32a8ecfebc4b3ccb5ad8,NaN,NaN,NaN,NaN
3,0,\nAttached are the two files with this week's ...,FW: Nuclear Rolling Forecast,22847680.1075863611080.JavaMail.evans@thyme,normal,"[{'address': 'rika.imai@enron.com', 'name': ''}]","[{'address': 'russell.ballato@enron.com', 'nam...",2001-08-15T12:46:47.000Z,<22847680.1075863611080.JavaMail.evans@thyme>,"Wed, 15 Aug 2001 05:46:47 -0700 (PDT)",...,,,"\ExMerge - Benson, Robert\Inbox\Large Messages",BENSON-R,rob benson 6-25-02.PST,0ca99267aa67cfe2acf078403ea861ae,NaN,NaN,NaN,NaN
4,0,lm:\nWhat are your thoughts going forward........,hello,15012282.1075852957298.JavaMail.evans@thyme,normal,"[{'address': 'jennifer.fraser@enron.com', 'nam...","[{'address': 'larry.may@enron.com', 'name': ''}]",2001-10-03T07:35:05.000Z,<15012282.1075852957298.JavaMail.evans@thyme>,"Wed, 3 Oct 2001 00:35:05 -0700 (PDT)",...,,,\LMAY2 (Non-Privileged)\Inbox,May-L,LMAY2 (Non-Privileged).pst,4bd9af6f563313a2af55fc9e140f3e46,NaN,NaN,NaN,NaN

In [5]:
# based on https://www.analyticsvidhya.com/blog/2021/06/sentiment-analysis-using-nltk-a-practical-approach/

def punc_clean(text):
    a=[w for w in text if w not in st.punctuation]
    return ''.join(a)

def remove_stopword(text):
    stopword=nltk.corpus.stopwords.words('english')
    stopword.remove('not')
    a=[w for w in nltk.word_tokenize(text) if w not in stopword]
    return ' '.join(a)

def preprocess_text(df):
    df['sentiment_text'] =  df['text'].copy()
    df['sentiment_text'] = df['sentiment_text'].apply(punc_clean)
    df['sentiment_text'] = df['sentiment_text'].apply(remove_stopword)


# preprocess_text(df)
# df.head()

In [25]:
# old

# from sklearn.feature_extraction.text import TfidfVectorizer
# vectr = TfidfVectorizer(ngram_range=(1,2),min_df=1)
# vectr.fit(df['sentiment_text'])
# vect_X = vectr.transform(df['sentiment_text'])

In [ ]:
# old

# from sklearn.linear_model import LogisticRegression
# model = LogisticRegression()
# clf=model.fit(vect_X,df['sentiment_text'])
# clf.score(vect_X,df['sentiment_text'])*100

In [6]:
smaller_df = df.head(100)

preprocess_text(smaller_df)
smaller_df.head()

<ipython-input-5-60ac51ef8510>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sentiment_text'] =  df['text'].copy()
<ipython-input-5-60ac51ef8510>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sentiment_text'] = df['sentiment_text'].apply(punc_clean)
<ipython-input-5-60ac51ef8510>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sentiment_text'] = df['sentiment_text'].apply(remove_stopword)

,index,text,subject,messageId,priority,from,to,date,headers.message-id,headers.date,...,headers.eb35c1,headers.eb32c2,headers.?,headers.your office (jessica ramiez),headers.(lavorato's office),headers.re,headers.(maureen x31808),headers.mark's office - eb3325,"headers.interconnect""",sentiment_text
0,0,---------------------- Forwarded by Rika Imai/...,4 Month Rolling Forecast,88180.1075863689140.JavaMail.evans@thyme,normal,"[{'address': 'rika.imai@enron.com', 'name': ''}]","[{'address': 'john.forney@enron.com', 'name': ...",2001-05-08T15:37:00.000Z,<88180.1075863689140.JavaMail.evans@thyme>,"Tue, 8 May 2001 08:37:00 -0700 (PDT)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forwarded Rika ImaiNAEnron 05082001 0337 PM Da...
1,0,great,Re: Jim Simpson,4460514.1075857469666.JavaMail.evans@thyme,normal,"[{'address': 'hunter.shively@enron.com', 'name...","[{'address': 'richard.tomaski@enron.com', 'nam...",2000-06-21T09:01:00.000Z,<4460514.1075857469666.JavaMail.evans@thyme>,"Wed, 21 Jun 2000 02:01:00 -0700 (PDT)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,great
2,0,"oohh la la. who was your ""friend""? did you g...",Re: Re[2]:,2160301.1075858147494.JavaMail.evans@thyme,normal,"[{'address': 'matthew.lenhart@enron.com', 'nam...","[{'address': 'shelliott@dttus.com', 'name': ''}]",2000-08-16T10:03:00.000Z,<2160301.1075858147494.JavaMail.evans@thyme>,"Wed, 16 Aug 2000 03:03:00 -0700 (PDT)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,oohh la la friend guys read stories together g...
3,0,\nAttached are the two files with this week's ...,FW: Nuclear Rolling Forecast,22847680.1075863611080.JavaMail.evans@thyme,normal,"[{'address': 'rika.imai@enron.com', 'name': ''}]","[{'address': 'russell.ballato@enron.com', 'nam...",2001-08-15T12:46:47.000Z,<22847680.1075863611080.JavaMail.evans@thyme>,"Wed, 15 Aug 2001 05:46:47 -0700 (PDT)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Attached two files weeks Nuclear Rolling Forec...
4,0,lm:\nWhat are your thoughts going forward........,hello,15012282.1075852957298.JavaMail.evans@thyme,normal,"[{'address': 'jennifer.fraser@enron.com', 'nam...","[{'address': 'larry.may@enron.com', 'name': ''}]",2001-10-03T07:35:05.000Z,<15012282.1075852957298.JavaMail.evans@thyme>,"Wed, 3 Oct 2001 00:35:05 -0700 (PDT)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,lm What thoughts going forward Also seeing win...

In [8]:
# from sklearn.feature_extraction.text import TfidfVectorizer
# vectr = TfidfVectorizer(ngram_range=(1,2),min_df=1)
# vectr.fit(smaller_df['sentiment_text'])
# vect_X = vectr.transform(smaller_df['sentiment_text'])

In [9]:
# from sklearn.linear_model import LogisticRegression
# model = LogisticRegression()
# clf=model.fit(vect_X, smaller_df['sentiment_text'])
# clf.score(vect_X, smaller_df['sentiment_text'])*100

100.0

In [15]:
from nltk.sentiment import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')
sia = SentimentIntensityAnalyzer()
sia.polarity_scores("Wow, NLTK is really powerful!")

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/nicholasjricciardi/nltk_data...

{'neg': 0.0, 'neu': 0.295, 'pos': 0.705, 'compound': 0.8012}

In [19]:
def get_polarity_score(row):
    return sia.polarity_scores(row)

In [20]:
smaller_df['sia_polarity_score'] = smaller_df['sentiment_text'].apply(get_polarity_score)
smaller_df.head()

<ipython-input-20-8f8a6a77098a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  smaller_df['sia_polarity_score'] = smaller_df['sentiment_text'].apply(get_polarity_score)

,index,text,subject,messageId,priority,from,to,date,headers.message-id,headers.date,...,headers.eb32c2,headers.?,headers.your office (jessica ramiez),headers.(lavorato's office),headers.re,headers.(maureen x31808),headers.mark's office - eb3325,"headers.interconnect""",sentiment_text,sia_polarity_score
0,0,---------------------- Forwarded by Rika Imai/...,4 Month Rolling Forecast,88180.1075863689140.JavaMail.evans@thyme,normal,"[{'address': 'rika.imai@enron.com', 'name': ''}]","[{'address': 'john.forney@enron.com', 'name': ...",2001-05-08T15:37:00.000Z,<88180.1075863689140.JavaMail.evans@thyme>,"Tue, 8 May 2001 08:37:00 -0700 (PDT)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Forwarded Rika ImaiNAEnron 05082001 0337 PM Da...,"{'neg': 0.0, 'neu': 0.963, 'pos': 0.037, 'comp..."
1,0,great,Re: Jim Simpson,4460514.1075857469666.JavaMail.evans@thyme,normal,"[{'address': 'hunter.shively@enron.com', 'name...","[{'address': 'richard.tomaski@enron.com', 'nam...",2000-06-21T09:01:00.000Z,<4460514.1075857469666.JavaMail.evans@thyme>,"Wed, 21 Jun 2000 02:01:00 -0700 (PDT)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,great,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound..."
2,0,"oohh la la. who was your ""friend""? did you g...",Re: Re[2]:,2160301.1075858147494.JavaMail.evans@thyme,normal,"[{'address': 'matthew.lenhart@enron.com', 'nam...","[{'address': 'shelliott@dttus.com', 'name': ''}]",2000-08-16T10:03:00.000Z,<2160301.1075858147494.JavaMail.evans@thyme>,"Wed, 16 Aug 2000 03:03:00 -0700 (PDT)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,oohh la la friend guys read stories together g...,"{'neg': 0.0, 'neu': 0.561, 'pos': 0.439, 'comp..."
3,0,\nAttached are the two files with this week's ...,FW: Nuclear Rolling Forecast,22847680.1075863611080.JavaMail.evans@thyme,normal,"[{'address': 'rika.imai@enron.com', 'name': ''}]","[{'address': 'russell.ballato@enron.com', 'nam...",2001-08-15T12:46:47.000Z,<22847680.1075863611080.JavaMail.evans@thyme>,"Wed, 15 Aug 2001 05:46:47 -0700 (PDT)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Attached two files weeks Nuclear Rolling Forec...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
4,0,lm:\nWhat are your thoughts going forward........,hello,15012282.1075852957298.JavaMail.evans@thyme,normal,"[{'address': 'jennifer.fraser@enron.com', 'nam...","[{'address': 'larry.may@enron.com', 'name': ''}]",2001-10-03T07:35:05.000Z,<15012282.1075852957298.JavaMail.evans@thyme>,"Wed, 3 Oct 2001 00:35:05 -0700 (PDT)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,lm What thoughts going forward Also seeing win...,"{'neg': 0.0, 'neu': 0.818, 'pos': 0.182, 'comp..."

In [22]:
smaller_df['sia_polarity_score'][0]

{'neg': 0.0, 'neu': 0.963, 'pos': 0.037, 'compound': 0.3182}

In [31]:
def parse_polarity_score(row):
    print(row)
    score_dict = row['sia_polarity_score']
    row['sia_pos'] = score_dict['pos']
    row['sia_neg'] = score_dict['neg']
    row['sia_neu'] = score_dict['neu']
    row['sia_compound'] = score_dict['compound']

In [37]:
smaller_df['sia_pos'] = smaller_df['sia_polarity_score'].apply(lambda row: row['pos'])
smaller_df['sia_neg'] = smaller_df['sia_polarity_score'].apply(lambda row: row['neg'])
smaller_df['sia_neu'] = smaller_df['sia_polarity_score'].apply(lambda row: row['neu'])
smaller_df['sia_compound'] = smaller_df['sia_polarity_score'].apply(lambda row: row['compound'])

<ipython-input-37-074fe6b2919e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  smaller_df['sia_pos'] = smaller_df['sia_polarity_score'].apply(lambda row: row['pos'])
<ipython-input-37-074fe6b2919e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  smaller_df['sia_neg'] = smaller_df['sia_polarity_score'].apply(lambda row: row['neg'])
<ipython-input-37-074fe6b2919e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  smaller_df['sia_neu'] = smaller_df['sia_polarity_score'].apply(lambda row: row['neu'])
<ipython-input-37-074fe6b2919e>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  smaller_df['sia_compound'] = smaller_df['sia_polarity_score'].apply(lambda row: row['compound'])

In [97]:
from_email_list = []
for row in smaller_df.iterrows():
    from_email_list.append(row[1]['from'][0]['address'])
    
smaller_df['from_email'] = pd.DataFrame(from_email_list)

<ipython-input-97-b3f3d3238ab8>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  smaller_df['from_email'] = pd.DataFrame(from_email_list)

In [105]:
col_slice = ['from_email', 'sia_pos', 'sia_neg', 'sia_neu', 'sia_compound']
test_df = smaller_df[col_slice]

In [106]:
test_df.groupby(['from_email']).mean()

                              sia_pos   sia_neg   sia_neu  sia_compound
from_email
amador.granado@enron.com        0.158  0.000000  0.842000      0.296000
andy.zipper@enron.com           1.000  0.000000  0.000000      0.585900
andy@apbenergy.com              0.085  0.065000  0.850000      0.855500
april.hrach@enron.com           0.148  0.017000  0.835000      0.955900
ayueh@hotmail.com               0.319  0.000000  0.681000      0.792500
...                               ...       ...       ...           ...
vince.kaminski@enron.com        0.166  0.025333  0.808667      0.904233
wallstreet@chargingrhino.net    0.228  0.025000  0.747000      0.994300
webmaster@evomarkets.com        0.249  0.103000  0.648000      0.956500
yvette.connevey@enron.com       0.288  0.000000  0.712000      0.924600
zistlerf@wallacegarcia.com      0.069  0.014000  0.917000      0.790600

[87 rows x 4 columns]

In [107]:
test_df.groupby(['from_email']).max()

                              sia_pos  sia_neg  sia_neu  sia_compound
from_email
amador.granado@enron.com        0.158    0.000    0.842        0.2960
andy.zipper@enron.com           1.000    0.000    0.000        0.5859
andy@apbenergy.com              0.085    0.065    0.850        0.8555
april.hrach@enron.com           0.148    0.017    0.835        0.9559
ayueh@hotmail.com               0.319    0.000    0.681        0.7925
...                               ...      ...      ...           ...
vince.kaminski@enron.com        0.192    0.057    0.828        0.9919
wallstreet@chargingrhino.net    0.228    0.025    0.747        0.9943
webmaster@evomarkets.com        0.249    0.103    0.648        0.9565
yvette.connevey@enron.com       0.288    0.000    0.712        0.9246
zistlerf@wallacegarcia.com      0.069    0.014    0.917        0.7906

[87 rows x 4 columns]

In [108]:
test_df.groupby(['from_email']).min()

                              sia_pos  sia_neg  sia_neu  sia_compound
from_email
amador.granado@enron.com        0.158    0.000    0.842        0.2960
andy.zipper@enron.com           1.000    0.000    0.000        0.5859
andy@apbenergy.com              0.085    0.065    0.850        0.8555
april.hrach@enron.com           0.148    0.017    0.835        0.9559
ayueh@hotmail.com               0.319    0.000    0.681        0.7925
...                               ...      ...      ...           ...
vince.kaminski@enron.com        0.115    0.000    0.790        0.7964
wallstreet@chargingrhino.net    0.228    0.025    0.747        0.9943
webmaster@evomarkets.com        0.249    0.103    0.648        0.9565
yvette.connevey@enron.com       0.288    0.000    0.712        0.9246
zistlerf@wallacegarcia.com      0.069    0.014    0.917        0.7906

[87 rows x 4 columns]